apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service

resources:
  - namespace.yaml

helmCharts:
  - name: pp191225-api-service
    repo: https://thang2k6adu.github.io/backend-service-charts
    version: 0.1.0
    releaseName: user-service
    namespace: user-service
    valuesFile: values.yaml
