apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: livekit-server

resources:
  - namespace.yaml
  - sealed-secret.yaml
  - configmap.yaml

helmCharts:
  - name: livekit-server
    repo: https://helm.livekit.io
    version: 1.9.0
    releaseName: dev
    namespace: livekit-server
    valuesFile: values.yaml